jobs:
  coverage:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      run: mvn test jacoco:report coveralls:report -D repoToken=${{ secrets.coveralls_repo_token
        }}
name: Coverage
on:
  repository_dispatch:
    types: trigger-ga___coverage.yml
