jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Build and test
      run: 'mvn clean install

        mvn jacoco:report jacoco:report-integration

        '
    - continue-on-error: true
      name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: '*/target/site

          '
    strategy:
      matrix:
        java-version:
        - 8
name: Run tests on pull requests
on:
  repository_dispatch:
    types: trigger-ga___on-pr.yml
