jobs:
  tagged-release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        ref: master
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Configure Git user
      run: 'git config user.email "actions@github.com"

        git config user.name "GitHub Actions"

        '
    - continue-on-error: true
      id: changelog
      name: Generate changelog
      uses: metcalfc/changelog-generator@v0.4.4
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Build and deploy
      run: 'pwd

        git checkout -b release/${{ github.event.inputs.version }}

        echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md

        git add CHANGELOG.md

        git commit -m "Adding changelogs"

        git push origin release/${{ github.event.inputs.version }}

        mvn -B release:prepare -DreleaseVersion=${{ github.event.inputs.version }}
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=60

        '
    - continue-on-error: true
      name: Create pull request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.RELEASE_PR_WORKFLOW_TOKEN }}
        source_branch: release/${{ github.event.inputs.version }}
    - continue-on-error: true
      name: Create a new github release
      uses: ncipollo/release-action@v1
      with:
        artifacts: /home/runner/work/blueflood/blueflood/blueflood-all/target/blueflood-all-${{
          github.event.inputs.version }}-jar-with-dependencies.jar
        body: ${{ steps.changelog.outputs.changelog }}
        tag: blueflood-${{ github.event.inputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        java-version:
        - 8
name: Manual Release workflow
on:
  repository_dispatch:
    types: trigger-ga___release.yml
